version: '3.8'

services:
  backend:
    image: xmile/xistant:latest
    networks:
      - traefik_public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.services.portainer.loadbalancer.server.port=8000
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
      GOOGLE_CSE_ID: $GOOGLE_CSE_ID
      GOOGLE_API_KEY: $GOOGLE_API_KEY
      AUTH0_DOMAIN: $AUTH0_DOMAIN
      AUTH0_AUDIENCE: $AUTH0_AUDIENCE

networks:
  traefik_public:
    external: true
